[Shropshire] Add map for tilma assets
mysociety/fixmystreet.com pull request #25
Opened 2021-10-25 14:43 UTC by MorayMySoc

Commit with initial asset mapping

2021-10-28 11:43 UTC, davea requested changes
Couple of little things is all

2021-10-28 11:43 UTC, davea commented on layers/shropshire.map
> +    CONNECTION 'shropshire/CTGR'
Should this be `CTGR.gpkg`?

2021-10-28 11:43 UTC, davea commented on layers/shropshire.map
> +      "gml_central_asset_id_alias" "central_as"
As mentioned on Slack this can be removed (here and in other layers).

2021-11-01 20:45 UTC, davea approved these changes
One query but looks good 👍

2021-11-01 20:45 UTC, davea commented on layers/shropshire.map
> +    NAME "Street_Gazeteer"
Should this be `Street_Gazetteer` (typo) instead? (Sorry, should have spotted this sooner!)

2021-11-02 10:58 UTC, dracos approved these changes
Assuming they all work, looks good :)

2021-11-08 09:48 UTC, MorayMySoc commented
Merged into staging

2021-11-08 09:48 UTC, closed without merging